baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Home'
theme = 'ananke'

[params]
  custom_css = ["css/custom.css"]


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

  [[menu.main]]
    name = "Research"
    url  = "/research/"
    weight = 2

  [[menu.main]]
    name = "Teaching"
    url  = "/teaching/"
    weight = 3

